### ISSUE TITLE
请问rt5350-i2s这个驱动可以用与其他播放器吗？

### ISSUE THREAD

**Issue by uintvalue** [qdk0901/openwrt-rt5350#2]
比如用于mpg123、mpd或者mplayer之类？

**Comment by qdk0901** [comment]
需要播放器有DLNA Server功能，不太清楚你说的播放器有没有这功能
rt5350这边是跑gmediarender做DLNA render

**Comment by uintvalue** [comment]
DLNA应该是应用层的吧，我需要底层的I2S声卡的硬件驱动，因为不太懂，所以不知道你的rt5350-i2s是不是就是I2S声卡的硬件驱动？

**Comment by qdk0901** [comment]
嗯，是的，rt5350-i2s就是声卡驱动，准确的说，是soc驱动，除此之外，还要加codec驱动，machine层驱动，我测试的时候用的是es9023(源码里的es9038)这个codec，你如果用别的codec，还得自己做适配。
不过声卡驱动，跟mp123，mpd，mplayer这些应用层的程序，没什么关系。

**Comment by uintvalue** [comment]
如此的话，把这个驱动装上，任何播放器都是可以直接调用了对吧

**Comment by qdk0901** [comment]
是的，可以这么理解。
直接用这个驱动，你需要配es9023的codec板，正确的连到rt5350板上，声音就ok。
你也可以用usb声卡，那样简单。

**Comment by uintvalue** [comment]
USB声卡已经有了，但是我想把USB留给U盘，又不想挂个usb hub，所以想试试I2S声卡，多谢你的帮助~为了让RT5350给唱首歌可费了不少劲，若不是搜到了你的这个项目，我差点就放弃了。。。谢谢谢谢！！！

**Comment by uintvalue** [comment]
另外请问这个驱动兼容其他具有I2S接口的DAC芯片么？

**Comment by qdk0901** [comment]
es9023 codec板不用mclk，所以驱动里也没加mclk相关的配置，
如果DAC芯片需要mclk的话，就要改一下驱动，或者用外部晶振提供mclk
